use super::lower::KmpLowerer;
use super::plan::{KmpModule, KmpOptions, KmpOutputs};
use crate::ir::{AbiContract, contract::FfiContract};

pub struct KmpEmitter;

impl KmpEmitter {
    pub fn emit(contract: &FfiContract, abi: &AbiContract, options: &KmpOptions) -> KmpOutputs {
        let module = KmpLowerer::new(contract, abi).lower();
        Self::render(&module, options)
    }

    fn render(module: &KmpModule, options: &KmpOptions) -> KmpOutputs {
        let common_main_source = Self::render_common_main(module, options);
        let jvm_main_source = Self::render_jvm_main(module, options);
        let native_main_source = Self::render_native_main(module, options);
        let cinterop_def = Self::render_cinterop_def(options);

        KmpOutputs {
            common_main_source,
            jvm_main_source,
            native_main_source,
            cinterop_def,
        }
    }

    fn render_common_main(module: &KmpModule, options: &KmpOptions) -> String {
        let mut lines = Vec::new();
        lines.push("// Generated by BoltFFI. Do not edit.".to_string());
        lines.push(format!("package {}", options.package_name));
        lines.push(String::new());
        lines.push(format!("expect object {} {{", options.module_name));

        for function in &module.functions {
            let suspend_prefix = if function.is_async { "suspend " } else { "" };
            lines.push(format!(
                "    expect {}fun {}({}): {}",
                suspend_prefix,
                function.public_name,
                Self::signature_params(function),
                function
                    .return_type
                    .clone()
                    .unwrap_or_else(|| "Unit".to_string())
            ));
        }

        lines.push("}".to_string());
        lines.push(String::new());
        lines.join("\n")
    }

    fn render_jvm_main(module: &KmpModule, options: &KmpOptions) -> String {
        let mut lines = Vec::new();
        lines.push("// Generated by BoltFFI. Do not edit.".to_string());
        lines.push(format!("package {}", options.package_name));
        lines.push(String::new());

        for function in &module.functions {
            let alias = format!("__jvm_{}", function.public_name);
            lines.push(format!(
                "import {}.{} as {}",
                options.jvm_binding_package, function.public_name, alias
            ));
        }

        if !module.functions.is_empty() {
            lines.push(String::new());
        }

        lines.push(format!("actual object {} {{", options.module_name));

        for function in &module.functions {
            let params = Self::signature_params(function);
            let args = Self::call_args(function);
            let return_type = function.return_type.as_deref().unwrap_or("Unit");
            let alias = format!("__jvm_{}", function.public_name);
            let suspend_prefix = if function.is_async { "suspend " } else { "" };

            if function.return_type.is_none() {
                lines.push(format!(
                    "    actual {}fun {}({}): {} {{",
                    suspend_prefix, function.public_name, params, return_type
                ));
                lines.push(format!("        {}({})", alias, args));
                lines.push("    }".to_string());
            } else {
                lines.push(format!(
                    "    actual {}fun {}({}): {} = {}({})",
                    suspend_prefix, function.public_name, params, return_type, alias, args
                ));
            }
        }

        lines.push("}".to_string());
        lines.push(String::new());
        lines.join("\n")
    }

    fn render_native_main(module: &KmpModule, options: &KmpOptions) -> String {
        let mut lines = Vec::new();
        lines.push("// Generated by BoltFFI. Do not edit.".to_string());
        lines.push(format!("package {}", options.package_name));
        lines.push(String::new());

        for function in &module.functions {
            let alias = format!("__native_{}", function.ffi_symbol);
            lines.push(format!(
                "import {}.{} as {}",
                options.native_binding_package, function.ffi_symbol, alias
            ));
        }

        if !module.functions.is_empty() {
            lines.push(String::new());
        }

        lines.push(format!("actual object {} {{", options.module_name));

        for function in &module.functions {
            let params = Self::signature_params(function);
            let args = Self::call_args(function);
            let return_type = function.return_type.as_deref().unwrap_or("Unit");
            let alias = format!("__native_{}", function.ffi_symbol);
            let suspend_prefix = if function.is_async { "suspend " } else { "" };

            if function.return_type.is_none() {
                lines.push(format!(
                    "    actual {}fun {}({}): {} {{",
                    suspend_prefix, function.public_name, params, return_type
                ));
                lines.push(format!("        {}({})", alias, args));
                lines.push("    }".to_string());
            } else {
                lines.push(format!(
                    "    actual {}fun {}({}): {} = {}({})",
                    suspend_prefix, function.public_name, params, return_type, alias, args
                ));
            }
        }

        lines.push("}".to_string());
        lines.push(String::new());
        lines.join("\n")
    }

    fn render_cinterop_def(options: &KmpOptions) -> String {
        [
            "# Generated by BoltFFI. Do not edit.",
            &format!("headers = {}", options.header_file_name),
            &format!("package = {}", options.native_binding_package),
            &format!("linkerOpts = -l{}", options.library_name),
            "",
        ]
        .join("\n")
    }

    fn signature_params(function: &super::plan::KmpFunction) -> String {
        function
            .params
            .iter()
            .map(|param| format!("{}: {}", param.name, param.kotlin_type))
            .collect::<Vec<_>>()
            .join(", ")
    }

    fn call_args(function: &super::plan::KmpFunction) -> String {
        function
            .params
            .iter()
            .map(|param| param.name.clone())
            .collect::<Vec<_>>()
            .join(", ")
    }
}

#[cfg(test)]
mod tests {
    use super::KmpEmitter;
    use crate::render::kmp::plan::{KmpFunction, KmpModule, KmpOptions, KmpParam};

    fn test_options() -> KmpOptions {
        KmpOptions {
            package_name: "com.example.demo".to_string(),
            module_name: "DemoKmp".to_string(),
            jvm_binding_package: "com.example.demo.jvmffi".to_string(),
            native_binding_package: "com.example.demo.native".to_string(),
            header_file_name: "demo.h".to_string(),
            library_name: "demo".to_string(),
        }
    }

    fn test_module() -> KmpModule {
        KmpModule {
            functions: vec![KmpFunction {
                public_name: "echoI32".to_string(),
                ffi_symbol: "boltffi_echo_i32".to_string(),
                params: vec![KmpParam {
                    name: "value".to_string(),
                    kotlin_type: "Int".to_string(),
                }],
                return_type: Some("Int".to_string()),
                is_async: false,
            }],
        }
    }

    #[test]
    fn render_common_main_emits_expect_api() {
        let output = KmpEmitter::render_common_main(&test_module(), &test_options());

        assert!(output.contains("package com.example.demo"));
        assert!(output.contains("expect object DemoKmp"));
        assert!(output.contains("expect fun echoI32(value: Int): Int"));
    }

    #[test]
    fn render_common_main_marks_async_functions_suspend() {
        let mut module = test_module();
        module.functions[0].is_async = true;

        let output = KmpEmitter::render_common_main(&module, &test_options());

        assert!(output.contains("expect suspend fun echoI32(value: Int): Int"));
    }

    #[test]
    fn render_platform_actuals_reference_binding_packages() {
        let module = test_module();
        let options = test_options();

        let jvm = KmpEmitter::render_jvm_main(&module, &options);
        let native = KmpEmitter::render_native_main(&module, &options);

        assert!(jvm.contains("import com.example.demo.jvmffi.echoI32 as __jvm_echoI32"));
        assert!(native.contains(
            "import com.example.demo.native.boltffi_echo_i32 as __native_boltffi_echo_i32"
        ));
    }

    #[test]
    fn render_cinterop_def_includes_header_package_and_linker() {
        let def = KmpEmitter::render_cinterop_def(&test_options());

        assert!(def.contains("headers = demo.h"));
        assert!(def.contains("package = com.example.demo.native"));
        assert!(def.contains("linkerOpts = -ldemo"));
    }
}
