use super::lower::KmpLowerer;
use super::plan::{KmpModule, KmpOptions, KmpOutputs};
use crate::ir::{AbiContract, contract::FfiContract};

pub struct KmpEmitter;

impl KmpEmitter {
    pub fn emit(contract: &FfiContract, abi: &AbiContract, options: &KmpOptions) -> KmpOutputs {
        let module = KmpLowerer::new(contract, abi).lower();
        Self::render(&module, options)
    }

    fn render(module: &KmpModule, options: &KmpOptions) -> KmpOutputs {
        let common_main_source = Self::render_common_main(module, options);
        let jvm_main_source = Self::render_jvm_main(module, options);
        let native_main_source = Self::render_native_main(module, options);
        let cinterop_def = Self::render_cinterop_def(options);

        KmpOutputs {
            common_main_source,
            jvm_main_source,
            native_main_source,
            cinterop_def,
            supported_functions: module.functions.len(),
            skipped_functions: module.skipped_functions.clone(),
        }
    }

    fn render_common_main(module: &KmpModule, options: &KmpOptions) -> String {
        let mut lines = Vec::new();
        lines.push("// Generated by BoltFFI. Do not edit.".to_string());
        lines.push(
            "// KMP v1 emits facade wrappers for direct primitive sync free functions.".to_string(),
        );
        if !module.skipped_functions.is_empty() {
            lines.push("// Skipped functions (unsupported in KMP v1):".to_string());
            for name in &module.skipped_functions {
                lines.push(format!("// - {name}"));
            }
        }
        lines.push(format!("package {}", options.package_name));
        lines.push(String::new());
        lines.push(format!("expect object {} {{", options.module_name));

        for function in &module.functions {
            lines.push(format!(
                "    expect fun {}({}): {}",
                function.public_name,
                Self::signature_params(function),
                function
                    .return_type
                    .clone()
                    .unwrap_or_else(|| "Unit".to_string())
            ));
        }

        lines.push("}".to_string());
        lines.push(String::new());
        lines.join("\n")
    }

    fn render_jvm_main(module: &KmpModule, options: &KmpOptions) -> String {
        let mut lines = Vec::new();
        lines.push("// Generated by BoltFFI. Do not edit.".to_string());
        lines.push(format!("package {}", options.package_name));
        lines.push(String::new());

        for function in &module.functions {
            let alias = format!("__jvm_{}", function.public_name);
            lines.push(format!(
                "import {}.{} as {}",
                options.jvm_binding_package, function.public_name, alias
            ));
        }

        if !module.functions.is_empty() {
            lines.push(String::new());
        }

        lines.push(format!("actual object {} {{", options.module_name));

        for function in &module.functions {
            let params = Self::signature_params(function);
            let args = Self::call_args(function);
            let return_type = function.return_type.as_deref().unwrap_or("Unit");
            let alias = format!("__jvm_{}", function.public_name);

            if function.return_type.is_none() {
                lines.push(format!(
                    "    actual fun {}({}): {} {{",
                    function.public_name, params, return_type
                ));
                lines.push(format!("        {}({})", alias, args));
                lines.push("    }".to_string());
            } else {
                lines.push(format!(
                    "    actual fun {}({}): {} = {}({})",
                    function.public_name, params, return_type, alias, args
                ));
            }
        }

        lines.push("}".to_string());
        lines.push(String::new());
        lines.join("\n")
    }

    fn render_native_main(module: &KmpModule, options: &KmpOptions) -> String {
        let mut lines = Vec::new();
        lines.push("// Generated by BoltFFI. Do not edit.".to_string());
        lines.push(format!("package {}", options.package_name));
        lines.push(String::new());

        for function in &module.functions {
            let alias = format!("__native_{}", function.ffi_symbol);
            lines.push(format!(
                "import {}.{} as {}",
                options.native_binding_package, function.ffi_symbol, alias
            ));
        }

        if !module.functions.is_empty() {
            lines.push(String::new());
        }

        lines.push(format!("actual object {} {{", options.module_name));

        for function in &module.functions {
            let params = Self::signature_params(function);
            let args = Self::call_args(function);
            let return_type = function.return_type.as_deref().unwrap_or("Unit");
            let alias = format!("__native_{}", function.ffi_symbol);

            if function.return_type.is_none() {
                lines.push(format!(
                    "    actual fun {}({}): {} {{",
                    function.public_name, params, return_type
                ));
                lines.push(format!("        {}({})", alias, args));
                lines.push("    }".to_string());
            } else {
                lines.push(format!(
                    "    actual fun {}({}): {} = {}({})",
                    function.public_name, params, return_type, alias, args
                ));
            }
        }

        lines.push("}".to_string());
        lines.push(String::new());
        lines.join("\n")
    }

    fn render_cinterop_def(options: &KmpOptions) -> String {
        [
            "# Generated by BoltFFI. Do not edit.",
            &format!("headers = {}", options.header_file_name),
            &format!("package = {}", options.native_binding_package),
            &format!("linkerOpts = -l{}", options.library_name),
            "",
        ]
        .join("\n")
    }

    fn signature_params(function: &super::plan::KmpFunction) -> String {
        function
            .params
            .iter()
            .map(|param| format!("{}: {}", param.name, param.kotlin_type))
            .collect::<Vec<_>>()
            .join(", ")
    }

    fn call_args(function: &super::plan::KmpFunction) -> String {
        function
            .params
            .iter()
            .map(|param| param.name.clone())
            .collect::<Vec<_>>()
            .join(", ")
    }
}
